import {faAngleLeft, faShieldHalved} from '@fortawesome/free-solid-svg-icons'
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {Link} from "react-router-dom";
import '../../styles/pages/ProvablyFair/provablyfair.scss';
import {Helmet} from "react-helmet";

function ProvablyFair() {
    return (
        <div className={'provably-fair'}>
            <main>
                <Helmet>
                    <title>Provably Fair Algorithm | GOdrop</title>
                    <meta name="description" content="My page description" />
                </Helmet>
                <div className={'provably-fair-wrapper container content'}>
                    <Link className={'go-back-link'} to={'/'}><FontAwesomeIcon icon={faAngleLeft} /> Go back</Link>
                    <h1 className={'page-header'}><FontAwesomeIcon icon={faShieldHalved} /> Provably Fair</h1>
                    <div className={'provably-fair-definition'}>
                        {/* eslint-disable-next-line react/no-unescaped-entities */}
                        <p>We prioritize fairness and transparency. That's why we have implemented Provably Fair to
                            ensure that every game outcome is unbiased and verifiable.</p>
                        <p>Our cryptographic algorithm generates random numbers and seeds that are
                            used to determine game outcomes. We ensure that there is now way to manipulate Provably Fair
                            algorithm and that all odds of winning on our site are equally random. <b>Every user has the same chance of winning an item.</b></p>
                        <p>Every roll result depends on three values:
                            <ul>
                                <li><dfn>Server Seed</dfn> - random value generated by the server. A new server seed is generated every 48 hours for each user. You can also generate a new server seed at anytime.</li>
                                <li><dfn>Client Seed</dfn> - random value generated by the user, it can also be set manually by the user</li>
                                <li><dfn>Nonce</dfn> - unique and incrementing value that resets every time a new server seed is generated.
                                    It guarantees that every roll result will be different.</li>
                            </ul>
                        </p>
                        <p>The result is calculated based on these values immediately prior to the start of each draw,
                            so the player can check the fairness of the draw immediately after opening a case.</p>
                        <p>Opening a case uses 2 nonce numbers - first for drawing the skin, second for drawing the skin float.</p>
                        <p>Secret Salt is an additional value used only in encrypting the public hash.</p>
                        <p>You will receive an encrypted server seed hash before opening a case. The initial and final hash
                            values will be identical, which will prove that the website has no influence on the final results of the draw.</p>
                    </div>
                </div>
            </main>
        </div>
    );
}

export default ProvablyFair;